create extension if not exists pgcrypto;

create table if not exists public.team_members (
  employee_name text primary key,
  email text,
  pin_hash text not null,
  is_active boolean not null default true
);

insert into public.team_members (employee_name, email, pin_hash)
values
  ('김동욱', null, crypt('1001', gen_salt('bf'))),
  ('서민진', null, crypt('1002', gen_salt('bf'))),
  ('정유석', null, crypt('1003', gen_salt('bf'))),
  ('장동호', null, crypt('1004', gen_salt('bf'))),
  ('이다연', null, crypt('1005', gen_salt('bf'))),
  ('장래홍', null, crypt('1006', gen_salt('bf'))),
  ('조예은', null, crypt('1007', gen_salt('bf'))),
  ('김형섭', null, crypt('1008', gen_salt('bf')))
on conflict (employee_name) do nothing;

create table if not exists public.weekly_reports (
  id bigint generated by default as identity primary key,
  employee_name text not null references public.team_members(employee_name),
  week_date date not null,
  prev_development text not null default '',
  prev_routine text not null default '',
  curr_development text not null default '',
  curr_routine text not null default '',
  business_trip text not null default '',
  etc text not null default '',
  status text not null check (status in ('draft', 'submitted')),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_name, week_date)
);

alter table public.team_members enable row level security;
alter table public.weekly_reports enable row level security;

revoke all on public.team_members from anon, authenticated;
revoke all on public.weekly_reports from anon, authenticated;

create or replace function public.get_weekly_report(
  p_employee_name text,
  p_week_date date,
  p_pin text
)
returns table (
  employee_name text,
  week_date date,
  prev_development text,
  prev_routine text,
  curr_development text,
  curr_routine text,
  business_trip text,
  etc text,
  status text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.team_members tm
    where tm.employee_name = p_employee_name
      and tm.is_active = true
      and tm.pin_hash = crypt(p_pin, tm.pin_hash)
  ) then
    raise exception '이름 또는 개인 비밀번호가 올바르지 않습니다.';
  end if;

  return query
  select
    wr.employee_name,
    wr.week_date,
    wr.prev_development,
    wr.prev_routine,
    wr.curr_development,
    wr.curr_routine,
    wr.business_trip,
    wr.etc,
    wr.status,
    wr.updated_at
  from public.weekly_reports wr
  where wr.employee_name = p_employee_name
    and wr.week_date = p_week_date;
end;
$$;

create or replace function public.save_weekly_report(
  p_employee_name text,
  p_week_date date,
  p_pin text,
  p_prev_development text,
  p_prev_routine text,
  p_curr_development text,
  p_curr_routine text,
  p_business_trip text,
  p_etc text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('draft', 'submitted') then
    raise exception '잘못된 제출 상태입니다.';
  end if;

  if not exists (
    select 1
    from public.team_members tm
    where tm.employee_name = p_employee_name
      and tm.is_active = true
      and tm.pin_hash = crypt(p_pin, tm.pin_hash)
  ) then
    raise exception '이름 또는 개인 비밀번호가 올바르지 않습니다.';
  end if;

  insert into public.weekly_reports (
    employee_name,
    week_date,
    prev_development,
    prev_routine,
    curr_development,
    curr_routine,
    business_trip,
    etc,
    status,
    submitted_at,
    updated_at
  )
  values (
    p_employee_name,
    p_week_date,
    coalesce(p_prev_development, ''),
    coalesce(p_prev_routine, ''),
    coalesce(p_curr_development, ''),
    coalesce(p_curr_routine, ''),
    coalesce(p_business_trip, ''),
    coalesce(p_etc, ''),
    p_status,
    case when p_status = 'submitted' then now() else null end,
    now()
  )
  on conflict (employee_name, week_date)
  do update set
    prev_development = excluded.prev_development,
    prev_routine = excluded.prev_routine,
    curr_development = excluded.curr_development,
    curr_routine = excluded.curr_routine,
    business_trip = excluded.business_trip,
    etc = excluded.etc,
    status = excluded.status,
    submitted_at = case
      when excluded.status = 'submitted' then now()
      else public.weekly_reports.submitted_at
    end,
    updated_at = now();
end;
$$;

create or replace function public.get_admin_weekly_reports(
  p_admin_password text,
  p_week_date date
)
returns table (
  employee_name text,
  email text,
  week_date date,
  prev_development text,
  prev_routine text,
  curr_development text,
  curr_routine text,
  business_trip text,
  etc text,
  status text,
  submitted_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  expected_password text := current_setting('app.admin_password', true);
begin
  if expected_password is null or expected_password = '' then
    raise exception 'Supabase 관리자 비밀번호 설정이 필요합니다.';
  end if;

  if p_admin_password <> expected_password then
    raise exception '관리자 비밀번호가 올바르지 않습니다.';
  end if;

  return query
  select
    tm.employee_name,
    tm.email,
    p_week_date,
    wr.prev_development,
    wr.prev_routine,
    wr.curr_development,
    wr.curr_routine,
    wr.business_trip,
    wr.etc,
    wr.status,
    wr.submitted_at,
    wr.updated_at
  from public.team_members tm
  left join public.weekly_reports wr
    on wr.employee_name = tm.employee_name
   and wr.week_date = p_week_date
  where tm.is_active = true
  order by array_position(
    array['김동욱','서민진','정유석','장동호','이다연','장래홍','조예은','김형섭'],
    tm.employee_name
  );
end;
$$;

grant execute on function public.get_weekly_report(text, date, text) to anon, authenticated;
grant execute on function public.save_weekly_report(text, date, text, text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_admin_weekly_reports(text, date) to anon, authenticated;

-- Supabase SQL Editor에서 아래 값을 실제 관리자 비밀번호로 변경해 실행하세요.
-- alter database postgres set app.admin_password = 'CHANGE_ME';
